### ISSUE TITLE
[Bug] Issue downloading from SonyLIV

### ISSUE THREAD

**Issue by AtomixAlpha** [meowcateatrat/elephant#18]
**FDM Version:** 6.21.0.5639
**Elephant Version:** 1.0.12

The SonyLIV links works fine while I download it using standalone yt-dlp. However, it fails with this addon. Is this an issue with FDM?

**FDM:**
![1](https://github.com/meowcateatrat/elephant/assets/93833292/568582c6-ad06-4c22-82d8-9f4bba6ef177)
![2](https://github.com/meowcateatrat/elephant/assets/93833292/5d9e20ff-2b23-4ca1-bd33-fce42dfad0fb)

**CMD:**
![3](https://github.com/meowcateatrat/elephant/assets/93833292/993f0759-40d7-4f30-8372-d665b2978d24)

**Comment by meowcateatrat** [comment]
This is an issue of FDM. I've reported it to its developers. Hope they will manage to fix it.
