### ISSUE TITLE
[Feature Request] Download high frame rate Youtube videos as MP4.

### ISSUE THREAD

**Issue by siswonugroho** [meowcateatrat/elephant#19]
Hi, thank you for this great extension.
As far as I know it's only possible to download high frame rate Youtube videos in WEBM format. Would you mind to make it possible for MP4 as well, which is more supported than WEBM?
Thank you.

**Comment by meowcateatrat** [comment]
Add-on can't download MP4 until a server provides content in MP4 format.
However, you should be able to convert downloaded WEBM to MP4 using FDM.
