### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CrypticCus** [meowcateatrat/elephant#2]
We can only download instagram videos,
Downloading story and image posts doesn't seem to work it returns as index. Can you fix thank you.

**Comment by meowcateatrat** [comment]
Please check with 1.0.2.

**Comment by CrypticCus** [comment]
this issue continues, instagram "image" posts return as index.html, "videos" are normal.

![image](https://user-images.githubusercontent.com/93516630/199064239-4bf7558c-8ef4-4faa-b692-805bc3f1cd31.png)
