### ISSUE TITLE
Missing quality options

### ISSUE THREAD

**Issue by kevingjs** [meowcateatrat/elephant#21]
### Problem:

Missing 720p in some videos and 1080p/1440p/2160p in all videos, also 60 FPS is missing too.

Is this a expected behavior or I messed up with something?

### Screenshots:

![video_to_download](https://github.com/meowcateatrat/elephant/assets/104476475/c850487d-cd3e-4c94-a1de-6a0e6ee06e05)

![FDM_download_video](https://github.com/meowcateatrat/elephant/assets/104476475/5a4d7fba-0012-448b-8e02-3a470bf3610a)

### Versions:

**Elephant:** `1.0.13`
**FDM:** `6.22.0.5714 (d2097ccf)`
**SO:** `Windows 10 Pro 21H2 (OS Build 19044.1766)`

**Comment by meowcateatrat** [comment]
Thank you for such a good report. However, I still need an example of URL where you experience these issue.

**Comment by kevingjs** [comment]
> Thank you for such a good report. However, I still need an example of URL where you experience this issue.

Here you go: https://www.youtube.com/watch?v=3ye5m-219-8

But like I told you, it's not just that one, it happens with all the YouTube videos I've tried today :(

**Comment by meowcateatrat** [comment]
@kevingjs I was able to reproduce this issue. Thanks for the report.

**Comment by FreeDownloadManagerTeam** [comment]
Please wait, I'll investigate it as soon as I have time. :) 
For now, I think it's FDM issue (I can be wrong).

**Comment by kevingjs** [comment]
> Please wait, I'll investigate it as soon as I have time. :) For now, I think it's FDM issue (I can be wrong).

Sure, no problem!

**Comment by meowcateatrat** [comment]
This is a bug of FDM. I've contacted their support. Hope they will manage to fix it.
