### ISSUE TITLE
Can't order playlist correctly

### ISSUE THREAD

**Issue by a04173c4** [meowcateatrat/elephant#23]
In short, the problem when I download playlist from YT, I can't watch them in ordered because sort by name didn't work if the filenames are not ordered. for example:
First video: Show arp list
Second video: Configure static arp
Third video: Prevent arp spoofing

I want it like this:
First video: 01-show arp list
Second video: 02-configure static arp
Third video: 03-prevent arp spoofing

Adding numeric prefix to playlist filenames will solve this problem.

**Comment by meowcateatrat** [comment]
I think it's a feature you would better ask FDM team about.
