### ISSUE TITLE
"Server has returned a web page

### ISSUE THREAD

**Issue by PepperMarioYT** [meowcateatrat/elephant#24]
i have the addon, but i tried to download consy from the channel "YOYLECAKE MICHAEL", but it game that error.

![image](https://github.com/user-attachments/assets/2ab621ef-1abc-4d92-af73-244f87353cd8)
![Screenshot 2024-07-11 204555](https://github.com/user-attachments/assets/7b5d79cd-e65e-4fd6-9720-c32afd9f6628)

here are screenshots

**Comment by meowcateatrat** [comment]
FDM version?

**Comment by PepperMarioYT** [comment]
FDM 6.22.0.5714 with elephant 1.0.16

**Comment by meowcateatrat** [comment]
Update your FDM to the latest one.
