### ISSUE TITLE
Server has return a web page

### ISSUE THREAD

**Issue by myth535** [meowcateatrat/elephant#25]
Sometimes the video is not catch and the text "Server has return a web page" is displayed. Happens right now with this video https://www.youtube.com/watch?v=-0c8HBgR5gw
![image](https://github.com/user-attachments/assets/fa727ccd-81b9-4a62-aeb7-16bbb29fe7e1)

**Comment by meowcateatrat** [comment]
Works fine for me. Make sure this link is playable in your web browser. Make sure you have the latest versions of both FDM and add-on installed.
