### ISSUE TITLE
Add Support for New Video Sites & YouTube MP3 Downloads

### ISSUE THREAD

**Issue by abdullah61830** [meowcateatrat/elephant#26]
I'd love to see support added for a few popular video streaming sites:

https://hdtoday.tv
https://hdtodayz.to
https://myflixerz.to
https://123moviesfree.net
https://gomovies.sx

Additionally, it would be fantastic to have the option to download YouTube videos directly as MP3 files.

**Why This Matters:**
**Broader Access:** Adding these sites means users can download from more sources, which is a big win.
**More Versatile:** The ability to convert YouTube videos to MP3 is super handy for those who only want the audio.

These features would make the tool even more powerful and user-friendly. Thanks for considering this!

**Comment by meowcateatrat** [comment]
Elephant is using [yt-dlp](https://github.com/yt-dlp/yt-dlp). You need to ask them to add support.
