### ISSUE TITLE
where to find download in link youtube of Elephant Youtube Downloader FDM 

### ISSUE THREAD

**Issue by Shujja-Ali** [meowcateatrat/elephant#27]
where to find download in link youtube of Elephant Youtube Downloader FDM ?

![Screenshot_2](https://github.com/user-attachments/assets/89535c9d-dd9d-45aa-af85-4f34b38f95b1)

**Comment by meowcateatrat** [comment]
1. Copy URL to your video from the address bar of your web browser.
2. Press "+" button in the FDM main window's panel, paste this URL and press OK button.
