### ISSUE TITLE
Shorts page return html page

### ISSUE THREAD

**Issue by VitaliyAT** [meowcateatrat/elephant#29]
FDM c080d283, Elephant 1.0.17

Before "\shorts" worked like playlist and be able download them all. Right now it write something like "Server returned html page". From one side: it's should be so and addon should parse it (I think it work so - maybe I am wrong) - and it should be OK if server returning html page, but in final it's no result - cant download anything.

@StephanieSanzo/shorts or @vladimirfitness/shorts - like checked example that not work for me

**Comment by meowcateatrat** [comment]
Please update both FDM and Elephant and try again.
