### ISSUE TITLE
yt-dlp dropping support for Python 3.8, Elephant will no longer support windows 7 32 bits os ? or Elephant will use alterantive yt-dlp made by Mr Nicolaasjan for 32 bits version and PythonWin7 Python 3.9+ installers that support Windows 7 SP1 and Windows Server 2008 R2 ?

### ISSUE THREAD

**Issue by trimechee** [meowcateatrat/elephant#30]
Hello Mr @meowcateatrat , i noticed when i installed FDM 32 bits for windows 7 os, and when i installed our beloved Elephant browser, Elepahnt Browser automatically installed Python 3.8, but yt-dlp will dropping support for Python 3.8 , does that mean Elepahnt will no longer support windows 7 32 bits os ? or Elephant will use alterantive yt-dlp 32 bits or 64 bits made by Mr Nicolaasjan ?

https://github.com/yt-dlp/yt-dlp/issues/10086

will Elepahnt 32 bts will install the newer PythonWin7 Python 3.9+ installers that support Windows 7 SP1 and Windows Server 2008 R2 ?

https://github.com/adang1345/PythonWin7

I have  great news taht may help Elephant to keep support for legacy os used by many users   !!

Mr Nicolaasjan offers us very precious advices and recommandations for compiling yt-dlp 32 bits / 64 bits and we hope surely it will help to integrate unofficial yt-dlp with Elephant Add-On please  ! : 

https://github.com/mhogomchungu/media-downloader/issues/465#issuecomment-2423759207

https://github.com/mhogomchungu/media-downloader/issues/465#issuecomment-2423761094

https://github.com/adang1345/PythonWin7

https://msfn.org/board/topic/183741-python-3813-for-windows-xp-sp3/page/2/#comment-1241782

https://msfn.org/board/topic/184368-who-here-has-a-youtube-dl-compile-for-winxp/page/9/

https://msfn.org/board/profile/414006-cmalex/

https://msfn.org/board/profile/347864-naaloh/

**Comment by meowcateatrat** [comment]
It's not possible to support Windows 7 which is not supported by everyone.

**Comment by trimechee** [comment]
Yes, we understand, thanks :)

i just say offically FDM keep support of windows 7 os which still has many users, so if Elephant extension continues to install on FDM 32 bits for windows 7 os, i thnink it will be good idea to save the planet from ecological disaster and electronic waste and help millions of people or humanitarian charities who still use recycled windows 7 machines, we hope our beloved Elephant will use this special updated python for windows 7, thanks !
