### ISSUE TITLE
Not working after latest FDM update

### ISSUE THREAD

**Issue by CrypticCus** [meowcateatrat/elephant#5]
Not working after latest FDM update, can u add support please thanks

**Comment by CrypticCus** [comment]
says python cant be found on logs. but its installed tried several versions of python.

**Comment by CrypticCus** [comment]
https://i2.paste.pics/ea343fb5083e03b7325f7a6fa1534a18.png?trs=468dc29fac871783a137698b3e82a82a8d3d9d33f126508ed09ac613a9dcfa92

https://www19.zippyshare.com/v/tKkrwWkX/file.html

**Comment by meowcateatrat** [comment]
You need to write to their support.

**Comment by CrypticCus** [comment]
thanks it was about python not recognized. i think fdm's fault... i installed python via fdm and now its working again.
