### ISSUE TITLE
Issue continues with latest elephant

### ISSUE THREAD

**Issue by CrypticCus** [meowcateatrat/elephant#6]
Only intagram videos can be dowloaded, pictures can't. it returns as html..... issue is not resolved. ytdlp supports it elephant has processing issues about this.

![image](https://user-images.githubusercontent.com/93516630/200111457-0e107d73-f370-4d72-b8ff-77536bd4ec6f.png)

**Comment by meowcateatrat** [comment]
Are you able to download pictures using yt-dlp (https://github.com/yt-dlp/yt-dlp)?

**Comment by CrypticCus** [comment]
its in the supported sites list... but it might be for videos only... maybe you can add support for images for various sites by adding https://github.com/mikf/gallery-dl

**Comment by meowcateatrat** [comment]
I don't think I have a will to do this (and also I suspect that FDM just does not support this yet).
