### ISSUE TITLE
[Bug] Only html is downloaded from VK video

### ISSUE THREAD

**Issue by iG8R** [meowcateatrat/elephant#9]
Hi.
The title says for itself.
For some reason, the plugin does not process videos from VK.

**Comment by iG8R** [comment]
For instance, https://vk.com/video-24440848_456240578 or https://vk.com/video/playlist/-24440848_54694294

**Comment by adem4ik** [comment]
1st link works for me: 
![image](https://user-images.githubusercontent.com/4707112/215195832-cd84bd5b-18b8-4f8e-a504-42e03f4f3e67.png)

Second link should work as it is just a playlist, not a link to the video.

**Comment by iG8R** [comment]
But in my case the situation is opposite :(

[FreeDownloadManager-VK-Video_2023-01-28_054104.webm](https://user-images.githubusercontent.com/11407417/215240939-8711a17f-eb39-49ef-8896-32607431d07d.webm)

PS. Here is the information about the add-on.
![FreeDownloadManager-Python-2023-01-28_054704](https://user-images.githubusercontent.com/11407417/215240791-3d9eb5e6-8710-42c6-a043-0f7489cd166e.jpg)

**Comment by iG8R** [comment]
Would like to add that Yuotube videos are downloaded OK.

**Comment by solidslave** [comment]
Hi. I have the same issue (only html) with YouTube and VK too.

**Comment by adem4ik** [comment]
Make sure you have installed the latest version, I don't have any of these problems with 1.0.6.

**Comment by solidslave** [comment]
I have 1.06 version. And few weeks all works fine..But then the download from YT stopped working. I think, this issue is linked with 'Python ver.’ OR ‘Multi Phyton versions in system', maybe. I work in MacOS Ventura, and i have few version of Phyton.

p. s. thanks for a great plugin, hopes, I can understand how to return the performance of the plugin.

**Comment by meowcateatrat** [comment]
"Pyhon 3.7 or higher is required" message - is an FDM issue. You need to contact their support.

**Comment by meowcateatrat** [comment]
Please check 1.0.12 version of the add-on. Please make sure you have the latest version of FDM.

**Comment by meowcateatrat** [comment]
Closing as staled.
